### ISSUE TITLE
Absolute  path in nlog.config

### ISSUE THREAD

**Issue by kgothatsotlaka** [CodeMazeBlog/.NET-Core-Series#2]
Hi, I'd like to know, since in the example you used absolute paths, will this approach not give us a problem during production? 

If so, how does one go about using relative paths ? 

Thanks

**Comment by MarinkoSpasojevic** [comment]
Hello. You have two solutions for this. In a production environment, you will have nlog.config file deployed as well, so you can change absolute locations to the right ones. 

Or you can change these absolute paths with relative ones: 
<target name="logfile" xsi:type="File"
            fileName="..\logs\${shortdate}_logfile.txt"
            layout="${longdate} ${level:uppercase=true} ${message}"/>
  </targets>

**Comment by kgothatsotlaka** [comment]
Thank you! I will try using the absolute path method for now
