### ISSUE TITLE
You Custom logging does not log the Controller name or Action name etc...

### ISSUE THREAD

**Issue by vcallegarip** [CodeMazeBlog/.NET-Core-Series#36]
How could you extend your custom logging service in order to log Controller name, classes name, action names, etc? Thank!

**Comment by CodeMazeBlog** [comment]
Well, the custom methods accept a string as a parameter, so you can provide the required information inside the string you send to the method. Or, you can add some additional parameters to those custom methods inside the LoggerManager class, and format the string to your needs.
