### ISSUE TITLE
Customer Registration changes

### ISSUE THREAD

**Issue by vipsahaj** [CodeMazeBlog/.NET-Core-Series#5]
Add fields on customer registration based on attached images. 
![Customer registration](https://user-images.githubusercontent.com/64739485/81466635-cc0ffd80-91f0-11ea-902c-f434d84f2eec.png)
![image_2020_05_06T15_11_31_109Z](https://user-images.githubusercontent.com/64739485/81466637-cd412a80-91f0-11ea-9470-23f6a01ee9d5.png)

**Comment by CodeMazeBlog** [comment]
I think you've reported to the wrong project ;)
