### ISSUE TITLE
Why not separate the CRUD to Services from Repository?

### ISSUE THREAD

**Issue by neonleo** [CodeMazeBlog/.NET-Core-Series#67]
Just study the part 17 - [IOwnerRepository.cs](https://github.com/CodeMazeBlog/.NET-Core-Series/blob/master/Part%2017/.NET%20Core%20part%20-%20end/Contracts/IOwnerRepository.cs)
The contract enforce the implement inside the Repository class, but is it better separate a Services layer for Owner , let say
OwnerService.cs and inject the corresponding repository to do the CRUD operation?

**Comment by CodeMazeBlog** [comment]
Yes, it is better to do that. Just this was a small project and we didn't want to complicate it even more. Also, if you read our Repository article again, you will find a link to the Onion Architecture article, which explains exactly how to use a Service layer in the project.
